# Generated by Django 3.2.7 on 2022-04-02 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='question ID')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.CharField(max_length=2000, verbose_name='text answer')),
                ('answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.answers', verbose_name='answers ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.option', verbose_name='option ID')),
            ],
        ),
    ]
