# Generated by Django 3.2.12 on 2022-04-21 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0002_question_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='question_id')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.CharField(max_length=2000, verbose_name='text_answer')),
                ('answers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.answer', verbose_name='answer_id')),
                ('option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.option', verbose_name='option_id')),
            ],
        ),
    ]
