# Generated by Django 4.0.3 on 2022-03-15 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answers_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_answer', to='answers.answers', verbose_name='answers ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='option_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_option', to='answers.answers', verbose_name='option ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='text_answer',
            field=models.CharField(default=1, max_length=2000, verbose_name='text answer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answers',
            name='question_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='question ID'),
            preserve_default=False,
        ),
    ]
