# Generated by Django 4.0.3 on 2022-03-21 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_option_content_option_question_question_content_and_more'),
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answers',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='answers.answers', verbose_name='answers ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='option',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='questions.option', verbose_name='option ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='text_answer',
            field=models.CharField(default=0, max_length=2000, verbose_name='text answer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='question ID'),
            preserve_default=False,
        ),
    ]
