# Generated by Django 4.0.3 on 2022-04-04 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_answer_answers_id_answer_option_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answers_ID',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='option_ID',
        ),
    ]
