# Generated by Django 4.0.3 on 2022-04-04 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_remove_answer_answers_id_remove_answer_option_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answers',
            new_name='answers_ID',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='option',
            new_name='option_ID',
        ),
    ]
