# Generated by Django 4.0.3 on 2022-04-04 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0004_rename_answers_answer_answers_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answers_ID',
            new_name='answers_id',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='option_ID',
            new_name='option_id',
        ),
        migrations.RenameField(
            model_name='answers',
            old_name='question_ID',
            new_name='question_id',
        ),
    ]
