# Generated by Django 4.0.3 on 2022-04-05 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0006_answerdetails_remove_answer_answers_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerdetails',
            name='answers_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.answer', verbose_name='answer ID'),
        ),
    ]
