# Generated by Django 3.2.7 on 2022-04-02 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='New poll', max_length=50)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('slug', models.TextField(editable=False, max_length=50, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='end date')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('filling', models.IntegerField(default=0)),
                ('sent', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Stopped'), (2, 'Waiting'), (3, 'Finished'), (4, 'Draft')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author ID')),
            ],
        ),
    ]
