# Generated by Django 4.0.3 on 2022-04-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='slug',
            field=models.TextField(editable=False, max_length=50, null=True, unique=True),
        ),
    ]
