# Generated by Django 4.0.3 on 2022-03-21 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='create date'),
        ),
        migrations.AddField(
            model_name='poll',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='poll',
            name='filling',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='poll',
            name='sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='slug',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start date'),
        ),
        migrations.AddField(
            model_name='poll',
            name='title',
            field=models.TextField(default='New poll', max_length=50),
        ),
    ]
