# Generated by Django 4.0.3 on 2022-03-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_author_poll_create_date_poll_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='is_active',
        ),
        migrations.AddField(
            model_name='poll',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Stopped'), (2, 'Waiting'), (3, 'Finished'), (4, 'Draft')], default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='slug',
            field=models.TextField(editable=False, max_length=50, null=True),
        ),
    ]
