# Generated by Django 4.0.3 on 2022-04-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_poll_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
