# Generated by Django 3.2.12 on 2022-04-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_poll_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Finished'), (2, 'Draft')], default=0),
        ),
    ]
