version: "3.8"

services:
  backend:
    build:
      context: ./backend
    image: pollingappregistry.azurecr.io/polling-app-backend
    command: /bin/sh /django/start-backend.sh
    ports:
      - 8000:8000
    depends_on:
      - db
    container_name: django-backend
    links:
      - db:db
    networks:
      - djangonetwork
  
  db:
    image: postgres
    env_file:
      - backend/.env
    container_name: postgres-db
    networks:
      - djangonetwork
  
  frontend:
    build:
      context: ./frontend/polling_app
    image: pollingappregistry.azurecr.io/polling-app-frontend
    depends_on:
      - backend
    container_name: angular2
    ports:
      - 80:80
    networks:
      - djangonetwork

networks:
  djangonetwork:
    driver: bridge
  
