version: "3.8"

services:
  backend:
    build:
      context: ./backend
    image: pastos/pollingapp-backend
    command: /bin/sh /django/start-backend.sh
    ports:
      - 8000:8000
    depends_on:
      - db
    container_name: django-backend
    links:
      - db:db
    networks:
      - djangonetwork
    volumes:
      - ./backend:/django
      - /django/venv
  
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - backend/.env
    container_name: postgres-db
    networks:
      - djangonetwork
  
  frontend:
    build:
      context: ./frontend/polling_app
    image: pastos/pollingapp-frontend
    volumes:
        - ./frontend/polling_app/:/usr/local/app
        - /usr/local/app/.angular2
        - /usr/local/app/node_modules
        - /usr/share/nginx/angular2
    depends_on:
      - backend
    ports:
      - 80:80
    networks:
      - djangonetwork

networks:
  djangonetwork:
    driver: bridge
  
