version: "3.8"

services:
  app:
    build: .
    ports:
      - 8000:8000
    image: polling-app-backend
    container_name: backend
    command: /bin/sh /django/start-backend.sh
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork
    volumes:
      - ./:/django
      - /django/venv

  db:
    image: postgres
    volumes:
      - ../data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgresql
    networks:
      - djangonetwork
      
networks:
  djangonetwork:
    driver: bridge
  
