version: "3.8"

services:
  app:
    build: .
    ports:
      - 8000:8000
    image: app:django
    container_name: django
    command: /bin/sh /django/start-backend.sh
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork
    volumes:
      - ./:/django
      - /django/venv

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - backend/.env
    container_name: postgresql
    networks:
      - djangonetwork
      
networks:
  djangonetwork:
    driver: bridge
  
