# Generated by Django 3.2.7 on 2022-04-02 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggering_answer', models.CharField(max_length=200, verbose_name='triggering answer')),
                ('triggered_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_triggered', to='questions.question')),
                ('triggering_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_triggering', to='questions.question')),
            ],
        ),
    ]
