# Generated by Django 4.0.3 on 2022-04-04 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('triggers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='triggered_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_triggered', to='questions.question'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='triggering_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_triggering', to='questions.question'),
        ),
    ]
