# Generated by Django 4.0.3 on 2022-03-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='company_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='company name'),
        ),
    ]
