# Generated by Django 3.2.7 on 2022-03-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='company_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='company name'),
        ),
    ]
