# Generated by Django 4.0.3 on 2022-03-21 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_author_poll_create_date_poll_description_and_more'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='content',
            field=models.CharField(default='Option', max_length=2000),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='question ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.CharField(default='Content', max_length=2000),
        ),
        migrations.AddField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.poll', verbose_name='poll ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='questions.questiontype', verbose_name='question ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questiontype',
            name='type_name',
            field=models.TextField(default='New question type'),
        ),
    ]
