# Generated by Django 3.2.12 on 2022-05-26 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_poll_status'),
        ('questions', '0003_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='polls.poll', verbose_name='poll ID'),
        ),
    ]
